# ###########################################################
# ### OPERON COMPLETION EVALUATION CONFIGURATION TEMPLATE ###
# ###########################################################
#
# Pipeline steps:
#   1. Generate operon completions from partial prompts using Evo.
#   2. Run Prodigal on concatenated sequences to obtain ORFs/proteins.
#   3. Filter proteins with segmasker, length, and partial-ORF heuristics.
#   4. Optionally align generated proteins to reference operon proteins via MAFFT,
#      producing per-gene and per-operon summaries.
# Requirements: Evo model + GPU, Prodigal, segmasker, MAFFT. Place all outputs in
# a single `output_dir` for easy inspection.
#
# OUTPUT FLOW
# -----------
# qc1: Generation log (`generated_sequences.csv`)
# qc2: DNA FASTA for downstream codon-aware tools (`all_sequences.fasta`)
# qc3: Prodigal results (`proteins.fasta`, `orfs.fasta`)
# qc4: Filtered proteins (`filtered_proteins.fasta`)
# qc5: Optional MAFFT-guided matches (`msa_filtered_proteins.fasta`, `sequence_alignment.csv`)
# qc6: Operon-level statistics (`msa_results.csv`, `summary_statistics.csv`)


###########################################
### 1. CORE INPUTS AND FILE LOCATIONS  ###
###########################################

# CSV of operon prompts (column order must match expectations in operon_completion.py)
input_prompts: ./sample_prompts/operon_completion_prompts.csv

# Reference operon proteins; headers should reference Expected_Response labels
reference_seqs: ./sample_reference_sequences/modabc_operon_sequences.fasta

# Directory for every generated artifact
output_dir: ./outputs/operon_completion

# segmasker binary location
segmasker_path: /usr/local/bin/ncbi-blast-2.16.0+/bin/segmasker

# MAFFT binary location
mafft_path: /usr/local/bin/mafft/bin/mafft


##################################
### 2. GENERATION PARAMETERS   ###
##################################

# Evo checkpoint name
model_name: evo-1.5-8k-base

# Number of DNA tokens to synthesize per prompt
n_tokens: 1500

# Sampling hyperparameters (temperature/top_k
# higher temperature increases diversity)
temperature: 0.7
top_k: 4

# Use batching to group prompts of equal length, increase to
# speed up sampling
batched: true
batch_size: 2

# Number of samples per operon completion prompt for evaluation
n_sample_per_prompt: 1


#################################################
### 3. FILTERING + ALIGNMENT CONFIGURATION   ###
#################################################

# Should reverse complements be considered downstream?
rc_truth: false

# Preserve both strands? (only meaningful if rc_truth true)
return_both: false

# Acceptable protein length range post-Prodigal (aa)
filter_min_length: 50
filter_max_length: 1200

# Filter partial ORFs flagged by Prodigal
filter_partial_bool: false

# Maximum allowed fraction of low-complexity residues from segmasker
segmasker_threshold: 0.1

# Enable MAFFT + reference scoring
run_msa: true

# Percent identity threshold for keeping alignments during reference filtering
seq_identity_match_threshold: 30.0
