# #######################################################################
# ### TOXIN–ANTITOXIN SAMPLING, FILTERING, AND CO-FOLD PREPARATION   ###
# #######################################################################
#
# This pipeline:
#   1. Generates DNA sequences from toxin–antitoxin prompts using Evo.
#   2. Runs Prodigal to call ORFs and translates them to protein sequences.
#   3. Applies complexity/length filters (segmasker + heuristics) to retain
#      tractable toxin/antitoxin proteins.
#   4. Uses ESMFold (optional) to score structural quality and keep only
#      confident folds.
#   5. Groups compatible toxin/antitoxin proteins, writes paired CSV/FASTA
#      outputs that can be fed into downstream co-folding workflows.
#
# By default the pipeline writes staged artifacts into `output_dir`
# so you can inspect every step or reuse intermediates.
#
# OUTPUT CHECKPOINTS
# ------------------
# qc1: Sampling metadata (`generated_sequences.csv`)
# qc2: DNA FASTA (`all_sequences.fasta`)
# qc3: Prodigal predictions (`proteins.fasta`, `orfs.fasta`)
# qc4: Filtered protein FASTA (`filtered_proteins.fasta`)
# qc5: ESMFold tables (`folds.csv`) and fold-filtered proteins (`filtered_folds.csv`)
# qc6: Paired candidate CSV/FASTA for downstream co-folding (`shared_protein_pairs.csv`, `cofold_targets.fasta`)


###########################################
### 1. CORE INPUTS AND FILE LOCATIONS  ###
###########################################

# CSV containing toxin–antitoxin prompts
input_prompts: ./sample_prompts/t2ta_sample_prompts.csv

# Directory that will receive all CSV/FASTA outputs listed above
output_dir: ./outputs/t2ta

# segmasker executable path for low-complexity filtering
segmasker_path: /usr/local/bin/ncbi-blast-2.16.0+/bin/segmasker


##################################
### 2. GENERATION PARAMETERS   ###
##################################

# Evo checkpoint name
model_name: evo-1.5-8k-base

# Number of DNA tokens to synthesize per prompt
n_tokens: 2000

# Sampling hyperparameters (temperature/top_k
# higher temperature increases diversity)
temperature: 0.8
top_k: 4

# Use batching to group prompts of equal length, increase to
# speed up sampling
batched: true
batch_size: 10

# Number of samples per prompt for evaluation
n_sample_per_prompt: 10


##############################################
### 3. FILTERING, FOLDING, AND CO-FOLDING ###
##############################################

# Should reverse complements be considered downstream?
rc_truth: true

# Preserve both strands? (only meaningful if rc_truth true)
return_both: true

# Acceptable protein length range post-Prodigal (aa)
filter_min_length: 50
filter_max_length: 300

# Filter partial ORFs flagged by Prodigal
filter_partial_bool: true

# Fraction of low-complexity positions tolerated before filtering
segmasker_threshold: 0.1

# Run ESMFold to score structures
run_esm_fold: true

# Minimum quality thresholds for keeping folded proteins
plddt_threshold: 0.6
ptm_threshold: 0.4
